name: Create Alfred Workflow Release

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - release

permissions:
  contents: write  # Allows creating and uploading to releases
  metadata: read   # Allows reading repository metadata

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Zip and rename workflow
      run: |
        cd src
        zip -r ../alfred-notes-workflow.zip .
        cd ..
        mv alfred-notes-workflow.zip alfred-notes-workflow.alfredworkflow

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: alfred-notes-workflow.alfredworkflow
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
